# Generated by Django 3.2.4 on 2021-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='enter course title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.FloatField(verbose_name='enter course amount')),
                ('duration', models.CharField(help_text='weeks, months, year', max_length=50, verbose_name='course duration')),
                ('is_availiable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
