# Generated by Django 3.2.4 on 2021-11-24 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0002_auto_20211124_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='on_leave',
            new_name='is_head_faculty',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='leave_duration',
        ),
        migrations.AddField(
            model_name='faculty',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Enter Birthday'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='employment_date',
            field=models.DateField(null=True, verbose_name='employed on'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='', verbose_name='profile image'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RequestLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField()),
                ('leave_duration', models.CharField(max_length=30, verbose_name='leave duration')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('granted', 'GRANTED'), ('rejected', 'REJECTED')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
